pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "${WORKSPACE}/.gocache"
                GOMODCACHE = "${WORKSPACE}/.gomodcache"
            }
            steps {
               dir('bugtracker-backend') {
                    sh 'mkdir -p $GOCACHE $GOMODCACHE'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}